### ISSUE TITLE
How is Inlets secured?

### ISSUE THREAD

**Issue by ehudkaldor** [inlets/inlets#202]
apologies for not using the template, but it's more of a question than a problem. Here goes:
how is the tunnel secured?

it probably sounds like silly question, but i could not find it in the docs or even in the code. and for now PRO is not something i can consider.

the README.md says `The tunnel link is secured via --token flag using a shared secret`, which makes me thing it does encrypt the content (though not sure what does that include - headers too?). But then 2 lines further down it notes `The default configuration uses websockets without SSL ws://, but to enable encryption you could enable SSL wss://`, which hints that maybe the transport itself is not secured, unless I enable SSL. can you clarify?

Also, there was a note in another issue saying there are instructions on how to enable TLS, but i could not find those instructions.

**Comment by alexellis** [comment]
Hi @ehudkaldor, thanks for your interest in inlets.

Authentication is via HTTP header on the control plane. The inlets OSS control-plane does not include TLS out of the box, but it's trivial to enable that using a reverse proxy and we do provide instructions.

However, as you're in doubt, then I would suggest you use [inlets PRO](https://github.com/inlets/inlets-pro) so that you get TLS out of the box without any further action required. It's also more powerful in that it supports TCP protocols.

For more on inlets PRO see: https://inlets.dev/

**Comment by alexellis** [comment]
>  and for now PRO is not something i can consider.

Why is that? It sounds like just what you need, in that it automates the parts you are uncertain on how to do yourself. So you get to lean on our expertise vs. trying to work it all out on your own.
